on: [push]

name: release

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    name: Build feelfree.tirol
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - name: build
        run: npm run build:gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
